skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
alexandria_audit = "Cgnt5epauqrsHCF9BhstkLyUVLjCnGP865bLJEqs22Y6"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
